### ISSUE TITLE
No Peasants spawning despite population limit is not reached (Legends of the Orient)

### ISSUE THREAD

**Issue by Xamroh1** [UnofficialCrusaderPatch/UnofficialCrusaderPatch#38] opened 2024-09-24 12:07 UTC
**Describe the bug**
Peasants are not spawning despite the population limit is not reached. The green circle timer for spawning keeps turning, but no peasants spawns.
Destroying houses until there a too little houses for the population and then rebuilding them, fixes the bug for a short amount of time.

**To Reproduce**
- until now this bug only occured with the modpack "Legends of the Orient"

**Expected behavior**

**Screenshots**
![Screenshot (1)](https://github.com/user-attachments/assets/257beaf7-e4fa-4771-9660-fd6943465bc0)
![Screenshot (2)](https://github.com/user-attachments/assets/cdbdee10-ce76-4159-8e15-242de5d6e2d9)

**Save game**

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Chrome
 - Version of the game: 1.41
 - Version of the UCP modding framework: 3.0.4
 - Version of the UCP GUI: 1.0.5

**Comment by gynt** [comment] 2024-09-24 19:57
Do you have any save games we can take a look at?

**Comment by Xamroh1** [comment] 2024-10-07 18:53
Here is a screenshot of my activated content. Couldn´t share the .yml file in this comment.
I can try to recreate this issue and create a save game.
Thank You!

![Screenshot 2024-10-07 205125](https://github.com/user-attachments/assets/d70c8ba2-6fdd-412c-a8d5-c3079a8926bb)

**Comment by gynt** [comment] 2024-10-11 07:38
Not much wrong with your config, although I can't see what is in your customisations. If you click on the "eye" icon you can copy paste the whole config or the `config-sparse` part and put it on discord!

**Comment by Heroesflorian** [comment] 2024-10-20 22:45
Note: Sounds like running into the SHC unit limit of 2500 - including animals, civilians and military units for all players combined. If that is the case, it is not a bug but the game basically "working as intended" (the game can't go beyond technical internal limits of the game). 

Quick solution for users: Play on SHC-Extreme instead (magic powers bar can be removed via UCP) to have a much higher unit limit of 1000. 

Idea for improvement: Display on-screen when the unit limit is reached, so players know what is happening. 
Such a display already exists in the map editor (active when 200 or less units are available until reaching the unit limit), stating "Available humans that can be placed: X". (Yes, the vanilla wording is not ideal, since this actually includes animals as well, but still.)
![image](https://github.com/user-attachments/assets/e54f5ac0-5811-4484-b8a3-8ef7fbd6c64a)

**Comment by Heroesflorian** [comment] 2024-10-21 20:53
Exactly!

**Comment by Heroesflorian** [comment] 2024-12-27 22:19
Closing this for now, as it is not a bug as originally reported, the confusion about what is happening has been cleared up, and the suggested improvement has been put into its own issue: 
https://github.com/UnofficialCrusaderPatch/UnofficialCrusaderPatch/issues/50

**Closed by Heroesflorian** 2024-12-27 22:19 UTC
Labels: duplicate, enhancement, has-proposal, feasible
